#!/bin/bash
#SBATCH -J test_add_job          
#SBATCH -p LocalQ          
#SBATCH -t 00:05:00         
#SBATCH --ntasks=1         
#SBATCH -o OUT/test.out
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=jldechow@unc.edu
#SBATCH --mem 1GB

set -x  # helpful debug: prints commands as they run

# Run the script
python3 "$1" $2 $3

# Bring results back to the submit directory
cp ./OUT/* "$HOME/OUT/"
